name: Backend Service

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Run Job'
        required: true
        default: 'build_deploy'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Install and Build 🔧
        run: mvn clean install -DskipTests=true
      - name: Heroku Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku plugins:install java
          heroku deploy:jar target/*.jar --app inventrymanagement-springboot
